### ISSUE TITLE
py2gift.core.build function problem

### ISSUE THREAD

**Issue by javovelez** [manuvazquez/py2gift#4]
Hello, thank you for this package! 

I started using the package for the first time today  and ran into the following problem when im trying to run py2gift.core.build:

if I don't put the "overwrite_existing_latex_files = True" argument, python tells me that it is missing. 

![image](https://user-images.githubusercontent.com/18739014/115304242-1ad15180-a13b-11eb-949f-63cd702badf2.png)

And if I place it, python tells me that it is left over.

![image](https://user-images.githubusercontent.com/18739014/115304127-f2495780-a13a-11eb-8aa7-a977bc76db7d.png)

Thank you!

**Comment by manuvazquez** [comment]
Ooops...it seems it was a versions mess. I have just upgraded both py2gift and gift-wrapper to try and fix this. It seems to be working fine again. Please update both py2gift and gift-wrapper and let me know how it goes.

**Comment by javovelez** [comment]
Thanks for the quick reply! Now it seems to work perfect. Thanks for sharing your code!
